config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/complete', to: 'lists#complete'

  resources :lists do
    resources :items
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates_presence_of :item_name

  def self.list_priority
  order(:priority)
  end

  def self.priority
    [1,2,3]
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :list
  before_action :item, except: [:index, :new, :create]
  def index
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    @item = @list.items.new(item_params)
    if @item.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to list_item_path(@list, @item)
    else
      redirect_to :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to list_path(@list)
  end

  private

    def item_params
      params.require(:item).permit(:item_name, :note, :completed, :priority)
    end

    def list
      @list = List.find(params[:list_id])
    end

    def item
      @item = @list.items.find(params[:id])
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :list, only: [:edit, :update, :destroy, :show]

  def index
    @lists = List.where(completed: false)
  end

  def show
    @items = @list.items.list_priority
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to lists_path(@list)
    else
      render :edit
    end
  end

  def complete
    @items = Item.where(completed: true)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end


  private

  def list_params
    params.require(:list).permit(:name, :date, :completed)
  end

  def list
    @list = List.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/items/_form.html.erb
<%= form_for [@list, @item] do |f| %>
  <%= f.label :item_name, 'Item Name'%>
  <%= f.text_field :item_name, required: true %>

  <br />
  <%= f.label :note %>
  <%= f.text_field :note %>
  <br />
  <%= f.label :priority %>
  <%= f.select :priority, Item.priority %>
  <br />
  <%= f.label :completed %>
  <%= f.radio_button :completed, :checked => true %>

<%= f.submit %>
<%end%>

app/views/items/edit.html.erb
<div>
  <h1> Edit Item: <%= @item.item_name %> </h1>
  <%= link_to 'Delete List?', list_item_path(@list), method: :delete, data: {confirm: 'Delete from list?'} %>

  <%= render(partial:'form') %>
  <br />
  <%=link_to '<< Back', lists_path(@list) %>
</div>

app/views/items/new.html.erb
<h1>Create an Item for <%= @list.name %></h1>

  <%= render(partial:'form') %>

  <%=link_to 'Back', lists_path %>

app/views/items/show.html.erb
<h2><%= @list.name %></h2>
<h3><%= @item.item_name %></h3>


  <p>notes: <%= @item.note %></p>
  <p><%= link_to 'Edit Item', edit_list_item_path(@list, @item) %></p>

  <%=link_to '<< Back', list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
    <%=link_to 'Home', root_path%> | <%=link_to 'To Do List', lists_path%> | <%=link_to 'Completed', complete_path%>
    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <%= f.label :name, 'List Name'%>
  <%= f.text_field :name, required: true %>

  <br />
  <%= f.label :date,'Created On' %>
  <%= f.date_field :date %>

<%= f.label :completed %>
<%= f.radio_button :completed, :checked => true %>

<%= f.submit %>
<%end%>

app/views/lists/_items.html.erb
<% if [@list, @items].any? %>

<ul>
  <% @items.each do |item| %>

    <li><%= link_to item.item_name, list_item_path(@list, item) %></li>

  <% end %>
</ul>


<% else %>
  <h3> No items in your list, Please Create One.</h3>
<% end %>

app/views/lists/complete.html.erb
<h1> You Are Done with These </h1>

<% @items.each do |item| %>
  <ul>
    <li><strong><%= item.item_name %></strong></li>
  </ul>
<% end %>

app/views/lists/edit.html.erb
<div>
  <h1> Edit List: <%= @list.name %> </h1>
  <%= link_to 'Delete List?', list_path(@list), method: :delete, data: {confirm: 'Delete whole list?'} %>

  <%= render(partial:'form') %>

  <%=link_to '<< Back', lists_path %>

</div>

app/views/lists/index.html.erb
<h1> Do Your To Do </h1>

<% if @lists.any? %>
<% @lists.each do |list| %>
  <h3><%= link_to list.name, list_path(list) %></h3>
<% end %>

<% else %>
  <p>You do no have any lists</p>
<% end %>
<p><%=link_to 'Add List', new_list_path %></p>

app/views/lists/new.html.erb
<h1>Create a New List</h1>

  <%= render(partial:'form') %>

  <%=link_to '<< Back', lists_path %>

app/views/lists/show.html.erb
<h1>Just Do Your List</h1>
<h2><%= @list.name %></h2>
<p><%=@list.date %></p>

  <%= render(partial:'items') %>

<%= link_to 'Add Items to List', new_list_item_path(@list) %>
<br />
<%=link_to 'Edit List Name', edit_list_path %>
<br />
<%= link_to 'Delete List?', list_path(@list), method: :delete, data: {confirm: 'Delete whole list?'} %>
<br />
<%=link_to '<< Back', lists_path %>

app/views/static_pages/home.html.erb
<div class="home">
  <h1>Welcome<br/>To Do List</h1>
  <h3>Get your stuff done today!</h3>
  <h2><%= link_to 'My To Do List', lists_path %></h2>
</div>